#!/bin/bash

echo "🚀 TaskFlow Deployment Checklist"
echo "================================"

echo ""
echo "📋 PRE-DEPLOYMENT CHECKS:"
echo "□ Push code to GitHub repository"
echo "□ Create Render account (render.com)"
echo "□ Create Netlify account (netlify.com)"
echo "□ Generate strong Django SECRET_KEY"
echo ""

echo "🔧 BACKEND (RENDER) SETUP:"
echo "□ Create new Web Service in Render"
echo "□ Connect GitHub repository"
echo "□ Set Root Directory: backend"
echo "□ Set Runtime: Python 3"
echo "□ Build Command: pip install -r requirements.txt && python manage.py collectstatic --noinput --clear"
echo "□ Start Command: gunicorn config.wsgi --bind 0.0.0.0:\$PORT"
echo ""

echo "🗄️ DATABASE SETUP:"
echo "□ Create PostgreSQL database in Render"
echo "□ Copy DATABASE_URL from Render database settings"
echo "□ Add DATABASE_URL to Render environment variables"
echo ""

echo "🌍 ENVIRONMENT VARIABLES (RENDER):"
echo "□ DJANGO_SECRET_KEY=<generated-key>"
echo "□ DJANGO_DEBUG=False"
echo "□ DJANGO_ALLOWED_HOSTS=<your-render-app.onrender.com>"
echo "□ DATABASE_URL=<postgresql://...>"
echo "□ CORS_ALLOWED_ORIGINS=<https://your-netlify-app.netlify.app>"
echo ""

echo "🎨 FRONTEND (NETLIFY) SETUP:"
echo "□ Create new site from Git"
echo "□ Set Base directory: frontend"
echo "□ Set Build command: npm run build"
echo "□ Set Publish directory: dist"
echo "□ Add environment variable: VITE_API_URL=<https://your-render-app.onrender.com/api>"
echo ""

echo "✅ POST-DEPLOYMENT:"
echo "□ Update Render CORS_ALLOWED_ORIGINS with Netlify domain"
echo "□ Test frontend loads correctly"
echo "□ Test API calls work (check browser network tab)"
echo "□ Create superuser if needed: python manage.py createsuperuser"
echo ""

echo "🔗 IMPORTANT URLs:"
echo "□ Render Backend: https://your-app-name.onrender.com"
echo "□ Netlify Frontend: https://your-site-name.netlify.app"
echo "□ Admin Panel: https://your-app-name.onrender.com/admin/"
echo ""

echo "🆘 TROUBLESHOOTING:"
echo "□ Check Render build logs for errors"
echo "□ Check Netlify deploy logs for build failures"
echo "□ Verify environment variables are set correctly"
echo "□ Test API endpoints directly in browser"
echo "□ Check CORS headers in browser dev tools"
echo ""

echo "🎉 Deployment Complete! Your TaskFlow app is live!"