# Generated by Django 6.0.4 on 2026-04-29 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskattachment',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='task',
            name='change_request_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='change_request_type',
            field=models.CharField(blank=True, choices=[('MAJOR', 'Major'), ('MINOR', 'Minor')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='dependencies',
            field=models.ManyToManyField(blank=True, help_text='Tasks that must be completed before this task can start.', related_name='blocked_tasks', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='dependency_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='display_id',
            field=models.IntegerField(editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='tasks.taskcomment'),
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=50)),
                ('new_status', models.CharField(max_length=50)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tasks.task')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
